//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaARD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillasVentas
    {
        public int Id { get; set; }
        public int Empleado_Id { get; set; }
        public decimal Pago_diario { get; set; }
        public int Dias_laborados { get; set; }
        public decimal Anticipos { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Categoria_Id { get; set; }
        public Nullable<int> Horas_extra { get; set; }
    
        public virtual CategoriasPlanillas CategoriasPlanillas { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
