//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaARD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes
    {
        public int Id { get; set; }
        public int Empleado_Id { get; set; }
        public decimal Sueldo { get; set; }
        public decimal Pago_Afp { get; set; }
        public decimal Pago_Isss { get; set; }
        public Nullable<decimal> Pago_Renta { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
