//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaARD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonosEmpleados
    {
        public int Empleado_Id { get; set; }
        public string Numero { get; set; }
        public int TipoTelefono_Id { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual TiposTelefonos TiposTelefonos { get; set; }
    }
}
